# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'ModulAid' do
  pod 'Firebase', '>= 2.5.0'
  pod 'LFHeatMap'
end

target 'ModulAidTests' do

end

target 'ModulAidUITests' do

end
